# Change these first
owner: elysiaroot # Your GitHub organization or username, where this repository lives
repo: "aniwork-uptime" # The name of this repository

sites:
  - name: "Aniwork Network"
    url: "https://ani.work/"
  - name: "Image-CDN"
    url: "https://cdn.ani.work/media_attachments/files/109/368/607/400/125/411/original/073fc528ace47db4.png"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.ani.work
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Aniwork Network Uptime
  introTitle: "Aniwork Uptime :-)"
  introMessage: "Aniwork!"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
